# Generated by Django 4.2.18 on 2025-01-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedpolicy',
            name='expired_on',
            field=models.DateTimeField(null=True),
        ),
    ]
