# Generated by Django 4.2.18 on 2025-02-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0002_alter_purchasedpolicy_expired_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasedpolicy",
            name="expired_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
